import './globals.css'

export const metadata = {
	title: 'SQL NoSQL Databases',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='antialiased grid justify-center'>{children}</body>
		</html>
	)
}
